### ISSUE TITLE
Tiup cannot detect server config field

### ISSUE THREAD

**Issue by hunterlxt** [pingcap-incubator/tiup#146]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

test encryption feature using tiup, just modify yaml file and expect to write tikv config here:
```
server_configs:
  tidb:
  tikv:
    encryption.method: "aes128-ctr"
    encryption.data-key-rotation-period: "14d"
    encryption.master-key.type: "file"
    encryption.master-key.method: "aes256-ctr"
    encryption.master-key.path: "/home/lxt/key/root.key"
    encryption.previous-master-key.type: "plaintext"

......
```
when I manually modify the `tikv.toml` in deploy directory, that works.

2. What did you expect to see?

encryption config is applied, but cluster is started normally.

3. What did you see instead?

is not applied

4. What version of TiUP are you using (`tiup --version`)?

tiup version v0.0.4 tiup
Go Version: go1.13
Git Branch: master
GitHash: ee569fb
Build Time: 2020-04-13 21:22:39 +0800
