### ISSUE TITLE
chown: invalid group

### ISSUE THREAD

**Issue by zhongzc** [pingcap-incubator/tiup#363]
Encountered some errors when experiencing the tiup-cluster simply.

With `topology.yaml`:
```
global:
  user: "zhongzc"
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

tidb_servers:
  - host: 127.16.5.32
    port: 40401
    status_port: 40402

tikv_servers:
  - host: 127.16.5.33
    port: 40403
    status_port: 40404

pd_servers:
  - host: 127.16.5.40
    client_port: 40405
    peer_port: 40406
```

Run:
```sh
$ tiup cluster deploy tidb-test v4.0.0-rc ${PWD}/topology.yaml
```

Said:
```sh
Starting /data2/zhongzc/.tiup/components/cluster/v0.4.6/cluster deploy tidb-test v4.0.0-rc /data2/zhongzc/tiup-cluster/topology.yaml 
Please confirm your topology:
TiDB Cluster: tidb-test
TiDB Version: v4.0.0-rc
Type  Host         Ports        Directories
----  ----         -----        -----------
pd    127.16.5.40  40405/40406  /tidb-deploy/pd-40405,/tidb-data/pd-40405
tikv  127.16.5.33  40403/40404  /tidb-deploy/tikv-40403,/tidb-data/tikv-40403
tidb  127.16.5.32  40401/40402  /tidb-deploy/tidb-40401
Attention:
    1. If the topology is not what you expected, check your yaml file.
    1. Please confirm there is no port/directory conflicts in same host.
Do you want to continue? [y/N]:  y
Input SSH password: 
+ Generate SSH keys ... Done
+ Download TiDB components
  - Download pd:v4.0.0-rc ... Done
  - Download tikv:v4.0.0-rc ... Done
  - Download tidb:v4.0.0-rc ... Done
  - Download node_exporter:v0.17.0 ... Done
[tiup-cluster-debug-2020-04-10-12-17-21.log](https://github.com/pingcap-incubator/tiup-cluster/files/4459862/tiup-cluster-debug-2020-04-10-12-17-21.log)

  - Download blackbox_exporter:v0.12.0 ... Done
+ Initialize target host environments
  - Prepare 127.16.5.40:22 ... Error
  - Prepare 127.16.5.33:22 ... Error
  - Prepare 127.16.5.32:22 ... Error

Error: executor.ssh.execute_failed: Failed to execute command over SSH for 'zhongzc@127.16.5.32:22' {ssh_stderr: chown: invalid group: 'zhongzc:zhongzc'
, ssh_stdout: , ssh_command: PATH=$PATH:/usr/bin:/usr/sbin sudo -H -u root bash -c "chown -R zhongzc:zhongzc {/tidb-deploy,/tidb-data}"}, cause: Process exited with status 1

Verbose debug logs has been written to /data2/zhongzc/.tiup/data/Rvj5jyX/tiup-cluster-debug-2020-04-10-12-17-21.log.
Error: start `/data2/zhongzc/.tiup/components/cluster/v0.4.6/cluster` (wd:/data2/zhongzc/.tiup/data/Rvj5jyX) failed: exit status 1
```

Log:
[tiup-cluster-debug-2020-04-10-12-17-21.log](https://github.com/pingcap-incubator/tiup-cluster/files/4459866/tiup-cluster-debug-2020-04-10-12-17-21.log)
