### ISSUE TITLE
check conflict Host in topo

### ISSUE THREAD

**Issue by july2993** [pingcap-incubator/tiup#379]
version:
b6509b926154828bcbfdf9903831da67c564d2b3

topo.yml:
```
tidb_servers:
  - host: 172.19.0.101
  - host: 172.19.0.101

pd_servers:
  - host: 172.19.0.102
  - host: 172.19.0.103
  - host: 172.19.0.103

tikv_servers:
  - host: 172.19.0.102
  - host: 172.19.0.103
  - host: 172.19.0.103
```

deploy cluster
result:
```
github.com/pingcap-incubator/tiops/pkg/task.Parallel.Execute.func1
	/Users/huangjiahao/go/src/github.com/pingcap-incubator/tiops/pkg/task/task.go:171
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
Error: Process exited with status 1
stderr: rm: cannot remove '/home/tidb/deploy/tidb-4000/bin/tidb-v4.0.0-beta.2-linux-amd64.tar.gz': No such file or directory

github.com/pingcap-incubator/tiops/pkg/task.(*CopyComponent).Execute
	/Users/huangjiahao/go/src/github.com/pingcap-incubator/tiops/pkg/task/copy_component.go:57
github.com/pingcap-incubator/tiops/pkg/task.Serial.Execute
	/Users/huangjiahao/go/src/github.com/pingcap-incubator/tiops/pkg/task/task.go:131
github.com/pingcap-incubator/tiops/pkg/task.Parallel.Execute.func1
	/Users/huangjiahao/go/src/github.com/pingcap-incubator/tiops/pkg/task/task.go:171
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```
